FROM golang:1.21.1 as bulid-env
LABEL author="Takahiro Muramoto"
LABEL version="1.0"

WORKDIR /app
RUN go install github.com/cosmtrek/air@v1.45.0
RUN go install github.com/go-delve/delve/cmd/dlv@v1.21.0

# COPY go.mod go.sum ./
# RUN go mod download

CMD ["air", "-c", ".air.toml"]