path:
  patterns: "patterns"
parser:
  worker: 4
  multilineWorker: 3
server:
  port: "8080"
  logDir: "/logs"
fullTextSearch:
  ftsScheme : "http"
  ftsHost: "es01"
  ftsPort: "9200"
  ftsBulkUnit: 10000