FROM golang:1.21.1 as bulid-env
LABEL author="Takahiro Muramoto"
LABEL version="1.0"
#### edit ####
WORKDIR /go/src/github.com/ek170/href-counter/
RUN go get -d -v golang.org/x/net/html
COPY app.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
##############

FROM gcr.io/distroless/base-debian12:latest
#### edit ####
WORKDIR /root/
COPY --from=bulid-env /go/src/github.com/alexellis/href-counter/app ./
CMD ["./app"]
##############